ES-295: Create How it Works Section
tiegehanley/tiege-web pull request #24
Opened 2021-01-25 22:26 UTC by velopfe

US: https://tiegehanley.atlassian.net/browse/ES-295

Evidence: 

![Screen Shot 2021-01-25 at 4 24 06 PM](https://user-images.githubusercontent.com/72627722/105773728-f8f47400-5f29-11eb-99bf-0fa26bd0637f.png)

![Screen Shot 2021-01-25 at 4 23 57 PM](https://user-images.githubusercontent.com/72627722/105773733-fd209180-5f29-11eb-84c9-776dfe4ac711.png)

2021-01-25 22:31 UTC, sharoncm-build commented on web/tailwind.config.js
> +        primary: '#2E6448',
I think this was removed by Mario's MR and moved to theme.js

2021-01-25 22:31 UTC, sharoncm-build commented on web/src/components/Article.js
> +import React from 'react'
Can we add tests for this component?

2021-01-25 22:34 UTC, velopfe commented on web/src/components/Article.js
> +import React from 'react'
@jmaroa @jmaroa what do you think?

2021-01-25 23:11 UTC, velopfe commented on web/src/components/Article.js
> +import React from 'react'
Added test in the newest commit

2021-01-25 23:12 UTC, velopfe commented on web/tailwind.config.js
> +        primary: '#2E6448',
solved in the newest commit

2021-01-25 23:15 UTC, sharoncm-build commented on web/src/components/Article/Article.test.js
> +    expect(headingResult).toHaveTextContent(heading)
This is redundant, so we can remove it. The same for line 30

2021-01-26 01:24 UTC, sharoncm-build approved these changes

2021-01-26 02:00 UTC, jmaroa requested changes

2021-01-26 02:00 UTC, jmaroa commented on web/src/components/sections/FLP/HowItWorks/HowItWorks.js
> +          <h1 id='howItWorks-tagline' className='font-gotham font-light text-xs md:text-lg'>
Please remove all font-gotham from all elements since this already added globally in the body as default.

2021-01-26 02:02 UTC, jmaroa commented on web/src/components/sections/FLP/HowItWorks/HowItWorks.module.scss
> +    @layer utilities {
If so, please remove it from here and use the same one used in Hero and Why Tiege sections.

2021-01-26 14:39 UTC, velopfe commented on web/src/components/sections/FLP/HowItWorks/HowItWorks.module.scss
> +    @layer utilities {
While hero has some of the same elements, HowItWorks component needed specific customization for the underline to show up correctly. I tried modifying the root style for both but the underline wouldn't show correctly for both.

2021-01-26 14:44 UTC, velopfe commented on web/src/components/Article/Article.test.js
> +    expect(headingResult).toHaveTextContent(heading)
Only those lines or should everything be removed from line 20 down to 30?

2021-01-26 14:52 UTC, sharoncm-build commented on web/src/components/Article/Article.test.js
> +    expect(headingResult).toHaveTextContent(heading)
Only those lines

2021-01-26 15:26 UTC, jmaroa approved these changes

2021-01-26 15:32 UTC, merged